name: "3-Schedule"

on:
    schedule:
      - cron: '*/5 * * * *'
      
jobs:
    test_schedule:
      runs-on: ubuntu-latest
      steps:
        - name: "Test Schedule"
          run: echo "Test Schedule at `date` "
          shell: bash


